Revision of Update 03-version-control.Rmd Language revised directly until line 324.
Questions and comments:
Line 104: Why is Linux in square brackets?
Line 154: I'm getting an error: 
> r3::check_git_config()
Error: 'check_git_config' is not an exported object from 'namespace:r3'
It could be simply because I just re-opened the R project I created in March, so maybe I'm missing some setup?
Line 269-71: Not quite sure whether this sentence is what you meant?
In Fig. 8.5 it's not clear to me why there are two connected boxes of each state?
Line 305: Nothing happens when I do this - I get a box up saying "nothing added to commit but untracked files present". Nothing shows up in the history tab either. I tried again after opening the Readme file in Rstudio - no difference. Should we stage the file?
Line 312: Should we add "and save the changes"? If I don't save, the changes don't show up for me in the Git interface. They do after I save.
Line 317: This was empty for me until I chose "master" on the drop-down menu just right of the "history" tab button.